# Generated by Django 5.0.6 on 2024-06-13 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appservidor', '0002_alter_librodb_autor_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librodb',
            name='autor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='appservidor.autordb'),
        ),
    ]
